version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3010:3010
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - .:/node_modules

  postgres:
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    image: postgres:13.3
    environment:
      PG_DATA: /var/lib/postgres/data

  # REDIS SUKA NE RABOTAET
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379